# Generated by Django 5.1.6 on 2025-02-22 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthconnect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosismodel',
            old_name='Age',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='patientgenarateresult',
            name='diagnosis',
        ),
        migrations.AlterField(
            model_name='diagnosismodel',
            name='test_result_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=255, null=True)),
                ('consultation_fee', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
